/*
The guessing project in C++ is a game designed to test the player’s luck and knowledge. The player needs to guess a random number generated by the computer.
If the player guesses right, they will win a certain amount of money. The winning prize depends on the difficulty of the game. The program implements classes,
functions, and user-defined data types. It also uses other features such as loops and conditionals to create a logical structure. Furthermore, it makes use of the
standard template library to implement basic operations and other data structures.

Technologies Required: C++ programming language, Object Oriented Programming(OOPS), Data Structures, Input/Output Streams, Memory Management, Standard Template Library(STL).
*/
#include <cstdlib>
#include <ctime>


class Casino 
{
	public:
		static int randomNumberGenerator() 
		{
			srand((unsigned)time(0));
			return (rand() % 10) + 1;
		}

		static bool guessingGame(int playerNumber) 
		{
			if (randomNumberGenerator() == playerNumber) { return true; }
			else { return false; }
		}
};